---
title: "Report"
author: "Randi Bolt"
date: "6/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# location of this file
here::i_am("00_R/report.Rmd")
# libaraies
library(NBAcharts)
library(plyr)
# location of data 
location_of_clean_data <- here::here("02_clean_data",
                                     "clean_data.rds")
# load data 
clean_data <- base::readRDS(location_of_clean_data)[[1]]
colors <- base::readRDS(location_of_clean_data)[[2]]
labels <- base::readRDS(location_of_clean_data)[[3]]
ring_labels <- base::readRDS(location_of_clean_data)[[4]]
# circ barplot
x <- circ_col_chart(player_data = clean_data,
               ring_scale = ring_labels[[1]],
               ring_inner = ring_labels[[2]],
               ring_middle = ring_labels[[3]],
               ring_outer = ring_labels[[4]],
               ringlab_inner = ring_labels[[5]],
               ringlab_middle = ring_labels[[6]],
               ringlab_outer = ring_labels[[7]],
               col_pal = colors,
               chart_title = labels[[1]],
               chart_subtitle = labels[[2]],
               chart_source = labels[[3]],
               cc_chart_filename = c("../03_figs/barchart.png"))
```

```{r, echo=FALSE}
x
```


