---
title: "clean data"
author: "Randi Bolt"
date: "6/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
here::i_am("05_sandbox/clean_data.Rmd")
which_stat <- "PTS"
```

```{r}
# libraries 
library(magrittr)
library(dplyr)

# location of data 
location_of_stats_raw <- here::here("01_raw_data",
                                    "raw_data_stats.rds")
location_of_colors_raw <- here::here("01_raw_data",
                                     "raw_data_colors.rds")

# load data 
colors <- base::readRDS(location_of_colors_raw)
ttl_stat <- base::readRDS(location_of_stats_raw)
```

```{r}
# load data 
colors <- base::readRDS(location_of_colors_raw)
ttl_stat <- base::readRDS(location_of_stats_raw)
# clean stat data -----------------------------------
# subset dataframe 
ttl_stat <- ttl_stat[[1]]

# rename column 2 to "Name"
base::names(ttl_stat)[2] <- "Name"

# Replace NA valuse with 0 (for stats)
ttl_stat[base::is.na(ttl_stat)] <- 0

# subset clean stat data ----------------------------
# subset Name and which_stat
subset_data <- ttl_stat %>%
  dplyr::select(Name, which_stat) %>%
  dplyr::rename(Name = Name,
                stat = which_stat) 

# select top 25% of players in this area
subset_data <- subset_data %>%
  dplyr::filter(stat >= base::unname(stats::quantile(subset_data$stat))[4])

subset_data

# clean colors data ---------------------------------
# subset to df 17 
colors_table <- colors[[17]]

# rename column 2 to "hex"
base::names(colors_table)[2] <- "hex"

# subset just the hex 
hex_codes <- colors_table$hex

# color palette 
col_pal <- colorRampPalette(hex_codes)(length(subset_data$Name))
```

```{r if else ring labels}
max_stat <- .55

if(max_stat > 50){
  ring_scale <- plyr::round_any(max_stat/3, 10)
  ring_inner <- ring_scale + 10
  ring_middle <- 2*ring_scale + 10 
  ring_outer <- 3*ring_scale + 10
  ringlab_inner <- base::as.character(ring_scale)
  ringlab_middle <- base::as.character(2*ring_scale)
  ringlab_outer <- base::as.character(3*ring_scale)
}else if(max_stat <= 50 && max_stat > 10){
  ring_scale <- plyr::round_any(max_stat/3, 1)
  ring_inner <- ring_scale + 5
  ring_middle <- 2*ring_scale + 5 
  ring_outer <- 3*ring_scale + 5
  ringlab_inner <- base::as.character(ring_scale)
  ringlab_middle <- base::as.character(2*ring_scale)
  ringlab_outer <- base::as.character(3*ring_scale)
}else if(max_stat <= 10 && max_stat > 1){
  ring_scale <- plyr::round_any(max_stat/3, .1)
  ring_inner <- ring_scale + 2
  ring_middle <- 2*ring_scale + 2 
  ring_outer <- 3*ring_scale + 2
  ringlab_inner <- base::as.character(ring_scale)
  ringlab_middle <- base::as.character(2*ring_scale)
  ringlab_outer <- base::as.character(3*ring_scale)
}else if(max_stat <= 1){
  ring_scale <- plyr::round_any(max_stat/3, .05)
  ring_inner <- ring_scale + .05
  ring_middle <- 2*ring_scale + .05 
  ring_outer <- 3*ring_scale + .05
  ringlab_inner <- base::as.character(ring_scale)
  ringlab_middle <- base::as.character(2*ring_scale)
  ringlab_outer <- base::as.character(3*ring_scale)
}
```






